---
title: "modeling-cpt"
author: "Linus"
date: "5 5 2021"
output: html_document
---

# value function

## for x >= 0

```{r}
x <- seq(0,10,.1) # outcomes
a <- seq(0.1,1,.1) # concave curvature for x >= 0 
output <- matrix(ncol = length(a), nrow = length(x)) # empty data frame for values 

for(i in seq_along(a)){# loop over different alpha-values  
  
 output[,i] <- x^a[i] # value function for x >= 0
 
 }

v_gain <- data.frame(x, output)
names(v_gain) <- c("x", paste("a =", a))
head(v_gain)
# plot 
v_gain_long <- gather(v_gain, alpha, y, "a = 0.1":"a = 1", factor_key=TRUE)
ggplot(data = v_gain_long) + 
  geom_line(aes(x = x, y = y, color = alpha))
```

## for y < 0

```{r}
v_loss <- v_gain*-1

v_loss_long <- gather(v_loss, alpha, y, "a = 0.1":"a = 1", factor_key=TRUE)

y2 <- rep(0, nrow(v_loss_long))
y3 <- rep(0, nrow(v_loss_long))
steep <- data.frame(y2, y3)
g <- c(2,3)

for (i in seq_along(g)) {
  
  steep[, i] <- g[i]*v_loss_long$y
  
}

v_loss_long <- bind_cols(v_loss_long, steep)
v_loss_long <- gather(v_loss_long, lambda, y, y:y3, factor_key=TRUE)
ggplot(data = v_loss_long) +
  geom_line(aes(x = x, y = y, color = lambda, linetype = alpha))
```

## for y < 0 <= x

```{r}
lambda <- factor(rep("y", nrow(v_gain_long)))
v_gain_long$lambda <- lambda

v <- bind_rows(v_gain_long, v_loss_long)
vfun <- ggplot(data = v) +
  geom_line(aes(x = x, y = y, color = lambda, linetype = alpha)) +
  geom_vline(xintercept = 0) + 
  geom_hline(yintercept = 0) + 
  ylim (-15, 10)
vfun
```




